"""Deterministic, scene-record answers for metadata questions -- "Where is
this?", "When was this taken?", "What sensor is this?", "What resolution?",
"What's in this scene?" -- fact retrieval, never asked of or generated by
an LLM. Every fact here is read directly off the scene's own record
(filename, sensor, GSD, mask) or, for location, off
data/benchmark/bigearthnet_txt_benchmark.csv's own real, dataset-provided
latitude/longitude/country columns -- never estimated, geocoded, or
invented. Per agent/dsl.py's execute(), every tool call's trace confidence
is 1.0; this module doesn't need its own confidence field for that reason
-- there is nothing uncertain about reading a fact off a record.
"""

import functools
import re
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from agent.vocabulary import SEGMENTATION_CLASSES
from evidence.ops import size as class_size

ROOT_DIR = Path(__file__).resolve().parent.parent
BENCHMARK_CSV = ROOT_DIR / "data" / "benchmark" / "bigearthnet_txt_benchmark.csv"

ASPECTS: tuple[str, ...] = ("location", "date", "sensor", "resolution", "classes")

# CLAUDE.md: "Minimum resolvable object size = 2.5 x GSD".
MIN_RESOLVABLE_FACTOR = 2.5

# Sentinel-2 product filenames embed their real acquisition date/time and
# platform (ESA's own naming convention, e.g.
# "S2A_MSIL2A_20170617T113321_N9999_R080_T29UPU_13_55" acquired 2017-06-17
# on Sentinel-2A) and MGRS tile id (T29UPU -> tile "29UPU"). Reading any of
# these back out is not fabrication -- it's the same genuine metadata the
# filename has always carried.
_DATE_RE = re.compile(r"_(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})_")
_PLATFORM_RE = re.compile(r"^(S2[AB])_")
_TILE_RE = re.compile(r"_T(\d{2}[A-Z]{3})_")


class MetadataError(ValueError):
    """Raised for an unknown `aspect`."""


@dataclass
class MetadataResult:
    aspect: str
    answer_text: str
    detail: dict = field(default_factory=dict)


@functools.lru_cache(maxsize=1)
def _tile_locations() -> dict[str, tuple[float, float, str]]:
    """MGRS tile id -> (latitude, longitude, country), averaged per tile
    from data/benchmark/bigearthnet_txt_benchmark.csv's own real,
    dataset-provided columns. Every patch sharing a tile comes from the
    same Sentinel-2 acquisition, so they agree on location/country --
    verified directly against this file: no tile spans more than one
    country. Returns {} if the benchmark CSV isn't present (data/download.py
    was never run) -- callers must then disclose location as unavailable,
    never guess one."""
    if not BENCHMARK_CSV.exists():
        return {}
    import pandas as pd  # local import: only this lookup path needs it

    df = pd.read_csv(BENCHMARK_CSV, usecols=["patch_id", "latitude", "longitude", "country"])
    df["tile"] = df["patch_id"].str.extract(_TILE_RE)
    grouped = df.dropna(subset=["tile"]).groupby("tile").agg(
        latitude=("latitude", "mean"), longitude=("longitude", "mean"), country=("country", "first"),
    )
    return {tile: (float(row.latitude), float(row.longitude), str(row.country)) for tile, row in grouped.iterrows()}


def parse_acquisition_date(filename: str) -> str | None:
    match = _DATE_RE.search(filename)
    if not match:
        return None
    year, month, day = match.group(1), match.group(2), match.group(3)
    return f"{year}-{month}-{day}"


def parse_platform(filename: str) -> str | None:
    match = _PLATFORM_RE.match(filename)
    return match.group(1) if match else None


def parse_tile(filename: str) -> str | None:
    match = _TILE_RE.search(filename)
    return match.group(1) if match else None


def tile_location(filename: str) -> tuple[float, float, str] | None:
    """(latitude, longitude, country) for `filename`'s MGRS tile, or None
    if the filename carries no tile id, or that tile isn't in the bundled
    benchmark CSV (true for most uploads, which have no BigEarthNet
    filename at all)."""
    tile = parse_tile(filename)
    if tile is None:
        return None
    return _tile_locations().get(tile)


def _location_result(filename: str) -> MetadataResult:
    location = tile_location(filename)
    if location is None:
        return MetadataResult(
            aspect="location",
            answer_text=(
                "This scene's location isn't available -- it doesn't carry a real Sentinel-2 "
                "tile reference this lookup depends on (true for most uploads)."
            ),
            detail={"available": False},
        )
    lat, lon, country = location
    return MetadataResult(
        aspect="location",
        answer_text=f"This scene is at approximately {lat:.3f}, {lon:.3f}, in {country}.",
        detail={"available": True, "latitude": lat, "longitude": lon, "country": country},
    )


def _date_result(filename: str) -> MetadataResult:
    date = parse_acquisition_date(filename)
    if date is None:
        return MetadataResult(
            aspect="date",
            answer_text="This scene's acquisition date isn't available -- its filename carries no "
                        "Sentinel-2 date stamp (true for most uploads).",
            detail={"available": False},
        )
    return MetadataResult(
        aspect="date", answer_text=f"This scene was acquired on {date}.",
        detail={"available": True, "acquisition_date": date},
    )


def _sensor_result(filename: str, sensor: str) -> MetadataResult:
    platform = parse_platform(filename)
    platform_text = f"Sentinel-2{platform[-1]}" if platform else "an unknown platform"
    return MetadataResult(
        aspect="sensor",
        answer_text=f"This scene is from {platform_text}, processed in '{sensor}' sensor mode.",
        detail={"platform": platform, "sensor_mode": sensor},
    )


def _resolution_result(gsd_metres: float) -> MetadataResult:
    min_resolvable_m = MIN_RESOLVABLE_FACTOR * gsd_metres
    return MetadataResult(
        aspect="resolution",
        answer_text=(
            f"{gsd_metres:.0f} m ground sample distance (per pixel). The smallest object this "
            f"scene can reliably resolve is about {min_resolvable_m:.1f} m across "
            f"({MIN_RESOLVABLE_FACTOR}x the GSD, per CLAUDE.md's minimum-resolvable-size rule) -- "
            "most individual buildings and vehicles can't be honestly counted at this resolution."
        ),
        detail={"gsd_metres": gsd_metres, "min_resolvable_m": min_resolvable_m},
    )


def _classes_result(mask: np.ndarray, metadata: dict) -> MetadataResult:
    present_ids = sorted(int(i) for i in np.unique(mask))
    entries: list[dict] = []
    for class_id in present_ids:
        area_ha = class_size(mask, class_id, metadata)
        if area_ha <= 0:
            continue
        entries.append({"class_name": SEGMENTATION_CLASSES[class_id], "area_ha": area_ha})
    entries.sort(key=lambda e: e["area_ha"], reverse=True)

    if not entries:
        answer_text = "No land-cover classes were detected in this scene."
    else:
        answer_text = "This scene contains: " + "; ".join(
            f"{e['class_name']} ({e['area_ha']:.2f} ha)" for e in entries
        ) + "."
    return MetadataResult(aspect="classes", answer_text=answer_text, detail={"classes": entries})


def scene_metadata(mask: np.ndarray, metadata: dict, aspect: str) -> MetadataResult:
    """Answers one metadata `aspect` about a scene. `metadata` is the same
    dict every evidence/ops.py tool receives (must carry `gsd_metres`),
    optionally enriched with `filename` and `sensor` (api/main.py's /query
    handler adds both from the scene's own database row) -- absent either,
    location/date/sensor answers degrade to an honest "not available"
    rather than guessing.
    """
    if aspect not in ASPECTS:
        raise MetadataError(f"unknown metadata aspect {aspect!r}; expected one of {ASPECTS}")

    filename = metadata.get("filename", "")
    if aspect == "location":
        return _location_result(filename)
    if aspect == "date":
        return _date_result(filename)
    if aspect == "sensor":
        return _sensor_result(filename, metadata.get("sensor", "unknown"))
    if aspect == "resolution":
        return _resolution_result(metadata["gsd_metres"])
    return _classes_result(mask, metadata)
