"""Short, scoped canned replies for a greeting or an off-topic question --
NOT a general chatbot. Per CLAUDE.md's "No pixel, no claim": nothing here
is asked of or generated by an LLM, and no raster is touched at all -- a
greeting or an off-topic question isn't about the scene, so there is
nothing to compute. These are fixed template strings, named by `kind`, not
a model's free-text guess.
"""

from dataclasses import dataclass

Kind = str  # "greeting" | "off_topic"

KINDS: tuple[str, ...] = ("greeting", "off_topic")

# A short, representative sample of what this system actually does --
# named once here so both reply templates below stay in sync with each
# other and with web/src/components/CommandBar.tsx's own example chips.
EXAMPLE_QUESTIONS: tuple[str, ...] = (
    "How many water bodies are there?",
    "What changed between these dates?",
    "Where is this?",
)

_WHAT_THIS_SYSTEM_DOES = (
    "counting and measuring land cover, describing a scene, comparing two dates, "
    "cross-checking optical against SAR, and answering questions about the scene itself "
    "(location, date, sensor, resolution)"
)


class ConversationalError(ValueError):
    """Raised for an unknown `kind`."""


@dataclass
class ConversationalReply:
    kind: str
    reply: str


def _example_suggestion() -> str:
    examples = '", "'.join(EXAMPLE_QUESTIONS)
    return f' For example: "{examples}".'


def reply(kind: str) -> ConversationalReply:
    if kind not in KINDS:
        raise ConversationalError(f"unknown conversational kind {kind!r}; expected one of {KINDS}")

    if kind == "greeting":
        text = f"Hi! I'm SatQuery AI -- I answer questions about the satellite scene loaded here: {_WHAT_THIS_SYSTEM_DOES}." + _example_suggestion()
    else:
        text = f"I only answer questions about the satellite scene currently loaded -- {_WHAT_THIS_SYSTEM_DOES}." + _example_suggestion()

    return ConversationalReply(kind=kind, reply=text)
